services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.1
    container_name: es
    environment:
      - discovery.type=single-node              # Run ES in single-node mode (no cluster formation)
      - xpack.security.enabled=false            # Disable authentication and security features
      - http.host=0.0.0.0                       # Bind to all network interfaces
      - ES_JAVA_OPTS=-Xms512m -Xmx512m          # Set JVM heap size (min and max 512 MB)
    ports:
      - "9200:9200"                             # Expose Elasticsearch HTTP API on port 9200
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -q '\"status\":\"green\"'"]
      interval: 10s                             # Check health every 10 seconds
      timeout: 5s                               # Timeout for health check
      retries: 10                               # Retry up to 10 times before marking as unhealthy

  grafana:
    image: grafana/grafana:10.1.2
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin        # Set default admin password (username is 'admin')
    ports:
      - "3000:3000"                             # Expose Grafana UI on port 3000
    depends_on:
      - elasticsearch                           # Wait for Elasticsearch to be healthy before starting
